version: "3.8"

services:
    backend:
        build: ./backend
        depends_on:
            - postgresql
        ports:
            - "8000:80"
        volumes:
            - ./backend/app:/app
    
    frontend:
        build: ./frontend
        ports:
            - "3000:80"
        volumes:
            - ./frontend:/app
    
    postgresql:
        image: postgres:12.2
        volumes:
            - postgres-db-data: /var/lib/postgresql/data/pgdata
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
    postgres-db-data:
       