version: "3.8"

services:
    backend:
        build: ./backend
        depends_on:
            - postgresql
        ports:
            - "8000:8000"
        volumes:
            - ./backend/app:/app
        env_file:
            - .env
    
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        stdin_open: true
        volumes:
            - /frontapp/node_modules
            - ./frontend/src:/frontapp/src
            - ./frontend/public:/frontapp/public
    
    postgresql:
        image: postgres:12.2
        volumes:
            - postgres-db-data:/var/lib/postgresql/data/pgdata
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
    postgres-db-data:
